BraveMvc/Controllers/AllGoodsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using PagedList;
using System.Web.Mvc;
using BLL;
using Models;
using DAL;
using IDAL;
using DALFactory;
using ViewModels;


namespace BraveMvc.Controllers
{
    public class AllGoodsController : Controller
    {
        // GET: AllGoods
        public ActionResult Index(String classifyInfoFrom, String SortInfoFrom, string currentFilter, int? page)
        {
           
            var goods = GoodsManage.FindGoods();
            if (classifyInfoFrom != null)
            {
                Session["fenlei"] = classifyInfoFrom;
            }
           
            if (classifyInfoFrom != null)
            {
                page = 1;
            }
            else
            {
                classifyInfoFrom = currentFilter;
            }

            ViewBag.CurrentFilter = classifyInfoFrom;
            if (SortInfoFrom != null)
            {
                page = 1;
            }
            else
            {
                SortInfoFrom = currentFilter;
            }
            ViewBag.CurrentFilter = SortInfoFrom;

            if (!string.IsNullOrEmpty(classifyInfoFrom))  //注意，判断字符串类型为空，要使用String.IsNullEmpty() 而不能使用 !=null 来判断。
            {
                goods = goods.Where(x => x.Classify.ClassifyName == classifyInfoFrom);
            }
            //ViewBag.searchString = searchString;
            if (!String.IsNullOrEmpty(SortInfoFrom))
            {
                if (Session["fenlei"] != null)
                {
                    var clssif = Session["fenlei"].ToString();
                    if (SortInfoFrom == "价格降序")
                    {
                        goods = goods.Where(x => x.Classify.ClassifyName == clssif).OrderByDescending(p => p.GoodsPrice);
                    }
                    else if (SortInfoFrom == "价格升序")
                    {
                        goods = goods.Where(x => x.Classify.ClassifyName == clssif).OrderBy(p => p.GoodsPrice);
                    }
                    else if (SortInfoFrom == "更新时间")
                    {
                        goods = goods.Where(x => x.Classify.ClassifyName == clssif).OrderByDescending(p => p.Grounding);
                    }
                }
                else
                {
                    if (SortInfoFrom == "价格降序")
                    {
                        goods = goods.OrderByDescending(p => p.GoodsPrice);
                    }
                    else if (SortInfoFrom == "价格升序")
                    {
                        goods = goods.OrderBy(p => p.GoodsPrice);
                    }
                    else if (SortInfoFrom == "更新时间")
                    {
                        goods = goods.OrderByDescending(p => p.Grounding);
                    }
                }
                


            }

            int pageSize = 9;
            int pageNumber = (page ?? 1);
            if (Request.IsAjaxRequest())
            {
                return PartialView("Index", goods.ToPagedList(pageNumber, pageSize));
            }
            else
            {
                return View("Index", goods.ToPagedList(pageNumber, pageSize));
            }
          
        }
        public ActionResult MiliVideo(int? page, string forumsectionid, string currentFilter)
        {
            var milivideo = ForumManage.findallvideo();
            if (forumsectionid != null)
            {
                page = 1;
            }
            else
            {
                forumsectionid = currentFilter;
            }

            ViewBag.CurrentFilter = forumsectionid;
            if (!string.IsNullOrEmpty(forumsectionid))
            {
               milivideo = milivideo.Where(p => p.ForumSection.ForumSectionName == forumsectionid);
            }
            int pagesize = 9;
            int pageNum = (page ?? 1);
            if (Request.IsAjaxRequest())
            {
                return PartialView("MiliVideo",milivideo.ToPagedList(pageNum,pagesize));
            }
            else
            {
                return View("MiliVideo", milivideo.ToPagedList(pageNum, pagesize));
            }



            
            
        }



        public ActionResult ForuEssa(int? page, string forumsectionid, string currentFilter)
        {
            var essayfgrgr = ForumManage.selectallforum();
            if (forumsectionid != null)
            {
                page = 1;
            }
            else
            {
                forumsectionid = currentFilter;
            }

            ViewBag.CurrentFilter = forumsectionid;
            if (!string.IsNullOrEmpty(forumsectionid))
            {
                essayfgrgr = essayfgrgr.Where(p => p.ForumSection.ForumSectionName == forumsectionid);
            }
            int pagesize = 8;
            int pageNum = (page ?? 1);
            if (Request.IsAjaxRequest())
            {
                return PartialView("ForuEssa", essayfgrgr.ToPagedList(pageNum, pagesize));
            }
            else
            {
                return View("ForuEssa", essayfgrgr.ToPagedList(pageNum, pagesize));
            }





        }
        public ActionResult Postdeadwe(int? page)
        {
            var pose = PostManage.selsectallsec().Skip(9);
            int pagesize = 9;
            int pageNum = (page ?? 1);
            if (Request.IsAjaxRequest())
            {
                return PartialView("Postdeadwe", pose.ToPagedList(pageNum, pagesize));
            }
            else
            {
                return View("Postdeadwe", pose.ToPagedList(pageNum, pagesize));
            }
           
           
           
        }
          

    
    }
}

BraveMvc/Views/AllGoods/ForuEssa.cshtml
@model PagedList.IPagedList<Models.Forum>
@using PagedList.Mvc
@{
    ViewBag.Title = "ForuEssa";
    Layout = null;
}
<div class="row">
    @foreach (var p in Model)
    {
        
            <div class="col-md-6 col-sm-6">
                <article class="blog-teaser">
                    <header>
                        <img src="@p.ForumImage" alt="">
                        <h3><a href="@Url.Action("EssayDetail","Forum", new { id = p.Forum_id})">@p.ForumName</a></h3>
                        <span class="meta">@p.ForumTime.ToString("MM-dd hh:mm")</span>
                        <hr>
                    </header>

                </article>
            </div>
       
    }
</div>
<div class="paging">
    @Html.PagedListPager(Model, page => Url.Action("ForuEssa", "AllGoods", new { page, currentFilter = ViewBag.CurrentFilter }),
    PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(
                 new AjaxOptions
                 {
                     HttpMethod = "GET",
                     InsertionMode = InsertionMode.Replace,
                     UpdateTargetId = "forumessaybut"

                 }
))
</div>

BraveMvc/Views/AllGoods/Index.cshtml
@model PagedList.IPagedList<Models.Goods>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Index";
    Layout = null;
}

    <style type="text/css">
        .page-list {
            margin-top: 10px;
        }
        .pageje{
            margin-top:3%;
        }
       .paging{
           text-align:right;
       }
    .sdsadas{
        height:100px;
    }
    </style>

 
    <div class="row classify-wuping" id="classifywuping">


        @foreach (var item in Model)
        {
            
            <div class="col-xs-6 col-sm-4 col-md-4 classify-wuping-list">

                <div class="classify-wuping-img" id="maximg">
                    <img src="@item.GoodsImage1" />
                </div>

                <div class="classify-wuping-content">
                    <h4 style="text-align:center">@item.GoodsName</h4>
                    <p>
                        <span style="float:left; margin-left:10px; color:red;font-size:20px">@item.GoodsPrice￥</span>
                         <div class="jiarugouwucart" style="float:right;height:30px;line-height:30px; width:100px;background-color:red;color:white;margin-right:10px; border-radius:5px; padding-left:20px; cursor:pointer; color:white" >
                             <a href="@Url.Action("Detail","Malls", new { id = @item.Goods_id,classid=@item.Classify_id })">立即购买</a>
                         </div>   
                      
                           
                      
                    </p>
                </div>

            </div>
           
        }
       
        <div class="row sdsadas">
            <div class="col-xs-6 col-sm-6 col-md-6"></div>
            <div class="col-xs-6 col-sm-6 col-md-6 paging">
                @Html.PagedListPager(Model, page => Url.Action("Index", "AllGoods", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }),
    PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(
                 new AjaxOptions
                 {
                     HttpMethod = "GET",
                     InsertionMode = InsertionMode.Replace,
                     UpdateTargetId = "classifywuping"

                 }
))
            </div>
          





        </div>

        </div>






   
  

BraveMvc/Views/AllGoods/MiliVideo.cshtml
@model PagedList.IPagedList<Models.MilitaryVideo>
@using PagedList.Mvc

@{
    ViewBag.Title = "MiliVideo";
    Layout = null;
}



<style type="text/css">
    .video-img{
        height:400px;
        width:100%;
        overflow:hidden;
   
    }
    .video-img-pu{
        overflow:hidden;
    }
    .video-img-pu img{
        height:300px;
        width:100%;
    }
     .video-img-pu img:hover{
         transform:scale(1.3,1.3);
     }
    .video-img p{
        width:100%;
        text-align:center;
        color:black;
        text-decoration:none;
            
    }
    .bofang_anniu{
        width:50px;
        height:50px;
        z-index:99;
        top:0%;
        position:absolute;
        border-radius:60px;
      display:none;
        
       
    }
     .bofang_anniu img{
         width:100%;
         height:100%;
        position:absolute;
        
     }
     .dsdhbofanganniu{
       margin-top:30%;
       margin-left:35%
     }
    
</style>


    <div class="row">
        @foreach (var o in Model)
        {

            <div class="col-xs-4 col-sm-4 col-md-4">
                <a href="@Url.Action("Detail","VideoDetail", new { id = o.MilitaryVideo_id,seectionid=o.ForumSection_id})">
                    <div class="video-img">
                        <div class="video-img-pu">
                            <img src="@o.MilitaryVideoImg" />
                          </div>
                        <div class="bofang_anniu">
                            <img src="~/Images/forum/timgbg1.png"/>
                        </div>
                        <p>@o.MilitaryVideoName</p>
                    </div>
                   
                </a>
                
            </div>
            
        }

    </div>
   
    

<div class="paging">
    @Html.PagedListPager(Model, page => Url.Action("MiliVideo", "AllGoods", new { page, currentFilter = ViewBag.CurrentFilter }),
    PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(
                 new AjaxOptions
                 {
                     HttpMethod = "GET",
                     InsertionMode = InsertionMode.Replace,
                     UpdateTargetId = "videoallbu"

                 }
))
</div>

<script type="text/javascript">
    $(".video-img-pu").hover(function () {
     
        $(this).siblings('.bofang_anniu').show(500).addClass('dsdhbofanganniu')


    },
    function () {
        $(this).siblings('.bofang_anniu').hide(500).removeClass('dsdhbofanganniu')





    })

</script>

 

BraveMvc/Views/AllGoods/Postdeadwe.cshtml
@model PagedList.IPagedList<Models.ForumSection>
@using PagedList.Mvc
@{
    ViewBag.Title = "Postdeadwe";
    Layout = null;

}

<div class="row">
    @foreach (var p in Model)
    {


        
            <div class="col-xs-6 col-sm-4 col-md-4">
               <div class="kuan_ssdw">
                   <a href="@Url.Action("JunBa","Forum", new { id = @p.ForumSection_id})">
                       <div class="row">
                           <div class="col-xs-6 col-sm-6 col-md-6 tupian_postba">
                               <img src="@p.FsectionImg" />
                           </div>
                           <div class="col-xs-6 col-sm-6 col-md-6 posetba_dec">
                               <div class="row">
                                   <span>@p.ForumSectionName </span>
                               </div>
                               <div class="row">
                                   <span>@Html.Raw((p.FSectionDes.Length > 20 ? p.FSectionDes.Substring(0, 18) : p.FSectionDes)) </span>
                               </div>
                           </div>
                       </div>

                   </a>
                  
                 
               </div>
            </div>
           
        
      
    }
</div>
<div class="paging">
    @Html.PagedListPager(Model, page => Url.Action("Postdeadwe", "AllGoods", new { page, currentFilter = ViewBag.CurrentFilter }),
    PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(
                 new AjaxOptions
                 {
                     HttpMethod = "GET",
                     InsertionMode = InsertionMode.Replace,
                     UpdateTargetId = "dkskdjeljlaksjde32"

                 }
))
</div>